"""Init models

Revision ID: 8c28bbc52c71
Revises: 
Create Date: 2026-09-28 16:31:04.604637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '8c28bbc52c71'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lightning_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('current_ka', sa.Float(), nullable=True),
    sa.Column('polarity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_lightning_events_location', 'lightning_events', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_lightning_events_event_time'), 'lightning_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_lightning_events_id'), 'lightning_events', ['id'], unique=False)
    op.create_table('nowcasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lead_time_minutes', sa.Integer(), nullable=False),
    sa.Column('affected_area', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('storm_intensity_class', sa.String(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_nowcasts_affected_area', 'nowcasts', ['affected_area'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_nowcasts_id'), 'nowcasts', ['id'], unique=False)
    op.create_index(op.f('ix_nowcasts_run_time'), 'nowcasts', ['run_time'], unique=False)
    op.create_table('nwp_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('run_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nwp_runs_id'), 'nwp_runs', ['id'], unique=False)
    op.create_index(op.f('ix_nwp_runs_model_name'), 'nwp_runs', ['model_name'], unique=False)
    op.create_index(op.f('ix_nwp_runs_run_time'), 'nwp_runs', ['run_time'], unique=False)
    op.create_table('radar_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.String(), nullable=False),
    sa.Column('scan_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_radar_scans_bbox', 'radar_scans', ['bbox'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_radar_scans_id'), 'radar_scans', ['id'], unique=False)
    op.create_index(op.f('ix_radar_scans_scan_time'), 'radar_scans', ['scan_time'], unique=False)
    op.create_index(op.f('ix_radar_scans_station_id'), 'radar_scans', ['station_id'], unique=False)
    op.create_table('satellite_frames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('satellite_name', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('scan_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_satellite_frames_bbox', 'satellite_frames', ['bbox'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_satellite_frames_id'), 'satellite_frames', ['id'], unique=False)
    op.create_index(op.f('ix_satellite_frames_satellite_name'), 'satellite_frames', ['satellite_name'], unique=False)
    op.create_index(op.f('ix_satellite_frames_scan_time'), 'satellite_frames', ['scan_time'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nowcast_id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('issue_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('alert_area', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['nowcast_id'], ['nowcasts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_alerts_alert_area', 'alerts', ['alert_area'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_nowcast_id'), 'alerts', ['nowcast_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
